import { mustGetAs } from "../core/dom";
import type { UiRefs } from "./refs";

export function createUiRefs(): UiRefs {
  return {
    skyCanvas: mustGetAs("skyCanvas", HTMLCanvasElement),
    lcCanvas: mustGetAs("lcCanvas", HTMLCanvasElement),
    btnStart: mustGetAs("btnStart", HTMLButtonElement),
    btnReset: mustGetAs("btnReset", HTMLButtonElement),
    btnClearLC: mustGetAs("btnClearLC", HTMLButtonElement),
    viewZoomEnabled: document.getElementById("viewZoomEnabled") as HTMLInputElement | null,
    btnZoomOut: document.getElementById("btnZoomOut") as HTMLButtonElement | null,
    btnZoomIn: document.getElementById("btnZoomIn") as HTMLButtonElement | null,
    btnZoomReset: document.getElementById("btnZoomReset") as HTMLButtonElement | null,
    zoomVal: document.getElementById("zoomVal"),
    timeSpeed: mustGetAs("timeSpeed", HTMLInputElement),
    timeSpeedMultiplier: mustGetAs("timeSpeedMultiplier", HTMLSelectElement),
    timeSpeedVal: mustGetAs("timeSpeedVal", HTMLElement),
    plotMode: document.getElementById("plotMode") as HTMLSelectElement | null,
    plotTrackingMode: document.getElementById("plotTrackingMode") as HTMLSelectElement | null,
    clampSmearedFlux: document.getElementById("clampSmearedFlux") as HTMLInputElement | null,
    viewAutoFit: document.getElementById("viewAutoFit") as HTMLInputElement | null,
    tVal: mustGetAs("tVal", HTMLElement),
    fluxVal: mustGetAs("fluxVal", HTMLElement),
    productModeSelect: mustGetAs("productModeSelect", HTMLSelectElement),
    uiModeSelect: mustGetAs("uiModeSelect", HTMLSelectElement),
    simModeSelect: document.getElementById("simModeSelect") as HTMLSelectElement | null,
    runtimeModeSelect: document.getElementById("runtimeModeSelect") as HTMLSelectElement | null,
    presetSelect: mustGetAs("presetSelect", HTMLSelectElement),
    presetDesc: mustGetAs("presetDesc", HTMLElement),
    realSystemSelect: document.getElementById("realSystemSelect") as HTMLSelectElement | null,
    realSystemMeta: document.getElementById("realSystemMeta"),
    skyBlackboxHint: document.getElementById("skyBlackboxHint"),
    plotModeVal: document.getElementById("plotModeVal") as HTMLSpanElement | null,
    warnVal: document.getElementById("warnVal") as HTMLSpanElement | null,
    nOccultersVal: document.getElementById("nOccultersVal") as HTMLSpanElement | null,
    vPlanetVal: document.getElementById("vPlanetVal") as HTMLSpanElement | null,
    vMoonVal: document.getElementById("vMoonVal") as HTMLSpanElement | null,
    timingHistoryVal: document.getElementById("timingHistoryVal") as HTMLSpanElement | null,
    didLessonStatus: document.getElementById("didLessonStatus"),
    didLessonSummary: document.getElementById("didLessonSummary"),
    didLessonMeta: document.getElementById("didLessonMeta"),
    didPhaseTitle: document.getElementById("didPhaseTitle"),
    didPhasePrompt: document.getElementById("didPhasePrompt"),
    didInterpretation: document.getElementById("didInterpretation"),
    didWorkedExample: document.getElementById("didWorkedExample"),
    didObservationList: document.getElementById("didObservationList"),
    didResponseComposer: document.getElementById("didResponseComposer"),
    didPrimaryResponseLabel: document.getElementById("didPrimaryResponseLabel"),
    didPrimaryResponseInput: document.getElementById("didPrimaryResponseInput") as HTMLTextAreaElement | null,
    didSecondaryResponseLabel: document.getElementById("didSecondaryResponseLabel"),
    didSecondaryResponseInput: document.getElementById(
      "didSecondaryResponseInput",
    ) as HTMLTextAreaElement | null,
    didResponseHelp: document.getElementById("didResponseHelp"),
    didFocusList: document.getElementById("didFocusList"),
    didHintList: document.getElementById("didHintList"),
    didMisconceptionList: document.getElementById("didMisconceptionList"),
    didCheckList: document.getElementById("didCheckList"),
    didFormulaList: document.getElementById("didFormulaList"),
    didCompareOut: document.getElementById("didCompareOut"),
    ocCanvas: document.getElementById("ocCanvas") as HTMLCanvasElement | null,
    ocBodySelect: document.getElementById("ocBodySelect") as HTMLSelectElement | null,
    ocUnitSelect: document.getElementById("ocUnitSelect") as HTMLSelectElement | null,
    ocTrendModeSelect: document.getElementById("ocTrendModeSelect") as HTMLSelectElement | null,
    ocExportBtn: document.getElementById("ocExportBtn") as HTMLButtonElement | null,
    ocClearBtn: document.getElementById("ocClearBtn") as HTMLButtonElement | null,
    ocStatsVal: document.getElementById("ocStatsVal"),
    ocFitVal: document.getElementById("ocFitVal"),
    didLessonSelect: document.getElementById("didLessonSelect") as HTMLSelectElement | null,
    didPrevBtn: document.getElementById("didPrevBtn") as HTMLButtonElement | null,
    didHintLevelSelect: document.getElementById("didHintLevelSelect") as HTMLSelectElement | null,
    didHintLessBtn: document.getElementById("didHintLessBtn") as HTMLButtonElement | null,
    didHintMoreBtn: document.getElementById("didHintMoreBtn") as HTMLButtonElement | null,
    didEventTargetSelect: document.getElementById("didEventTargetSelect") as HTMLSelectElement | null,
    didJumpEventBtn: document.getElementById("didJumpEventBtn") as HTMLButtonElement | null,
    didAutoAssess: document.getElementById("didAutoAssess") as HTMLInputElement | null,
    didCheckBtn: document.getElementById("didCheckBtn") as HTMLButtonElement | null,
    didNextBtn: document.getElementById("didNextBtn") as HTMLButtonElement | null,
    didExportBtn: document.getElementById("didExportBtn") as HTMLButtonElement | null,
    didComparePreset: document.getElementById("didComparePreset") as HTMLSelectElement | null,
    didCompareTime: document.getElementById("didCompareTime") as HTMLInputElement | null,
    didCompareBtn: document.getElementById("didCompareBtn") as HTMLButtonElement | null,
    didHypothesisSelect: document.getElementById("didHypothesisSelect") as HTMLSelectElement | null,
    didRevealSkyBtn: document.getElementById("didRevealSkyBtn") as HTMLButtonElement | null,
    didBinaryControls: document.getElementById("didBinaryControls"),
    btnApplyParams: mustGetAs("btnApplyParams", HTMLButtonElement),
    btnResetParams: mustGetAs("btnResetParams", HTMLButtonElement),
    observerX: mustGetAs("observerX", HTMLInputElement),
    observerY: mustGetAs("observerY", HTMLInputElement),
    observerZ: mustGetAs("observerZ", HTMLInputElement),
    overrideModeEl: document.getElementById("overrideMode") as HTMLInputElement | null,
    sliderRootEl: document.getElementById("sliderRoot") as HTMLElement | null,
    quickControlsRootEl: document.getElementById("quickControlsRoot") as HTMLElement | null,
    quickPlanetR: mustGetAs("quickPlanetR", HTMLInputElement),
    quickPlanetRVal: mustGetAs("quickPlanetRVal", HTMLElement),
    quickPlanetInc: mustGetAs("quickPlanetInc", HTMLInputElement),
    quickPlanetIncVal: mustGetAs("quickPlanetIncVal", HTMLElement),
    quickPlanetA: mustGetAs("quickPlanetA", HTMLInputElement),
    quickPlanetAVal: mustGetAs("quickPlanetAVal", HTMLElement),
    quickMoonEnabled: mustGetAs("quickMoonEnabled", HTMLInputElement),
    quickMoonR: mustGetAs("quickMoonR", HTMLInputElement),
    quickMoonRVal: mustGetAs("quickMoonRVal", HTMLElement),
    quickMoonA: mustGetAs("quickMoonA", HTMLInputElement),
    quickMoonAVal: mustGetAs("quickMoonAVal", HTMLElement),
    quickMoonInc: mustGetAs("quickMoonInc", HTMLInputElement),
    quickMoonIncVal: mustGetAs("quickMoonIncVal", HTMLElement),
    quickReflectedLight: mustGetAs("quickReflectedLight", HTMLInputElement),
    starR: mustGetAs("starR", HTMLInputElement),
    baselineFlux: mustGetAs("baselineFlux", HTMLInputElement),
    gridRes: mustGetAs("gridRes", HTMLInputElement),
    ldEnabled: mustGetAs("ldEnabled", HTMLInputElement),
    ldU1: mustGetAs("ldU1", HTMLInputElement),
    ldU2: mustGetAs("ldU2", HTMLInputElement),
    ldBandpass: mustGetAs("ldBandpass", HTMLInputElement),
    ldBands: mustGetAs("ldBands", HTMLInputElement),
    patchesEnabled: mustGetAs("patchesEnabled", HTMLInputElement),
    spotEvolutionEnabled: mustGetAs("spotEvolutionEnabled", HTMLInputElement),
    spotRotationPeriod: mustGetAs("spotRotationPeriod", HTMLInputElement),
    spotCoverage: mustGetAs("spotCoverage", HTMLInputElement),
    spotLifetime: mustGetAs("spotLifetime", HTMLInputElement),
    spotDriftRate: mustGetAs("spotDriftRate", HTMLInputElement),
    p1x: mustGetAs("p1x", HTMLInputElement),
    p1y: mustGetAs("p1y", HTMLInputElement),
    p1r: mustGetAs("p1r", HTMLInputElement),
    p1f: mustGetAs("p1f", HTMLInputElement),
    p2x: mustGetAs("p2x", HTMLInputElement),
    p2y: mustGetAs("p2y", HTMLInputElement),
    p2rx: mustGetAs("p2rx", HTMLInputElement),
    p2ry: mustGetAs("p2ry", HTMLInputElement),
    p2angle: mustGetAs("p2angle", HTMLInputElement),
    p2f: mustGetAs("p2f", HTMLInputElement),
    planetR: mustGetAs("planetR", HTMLInputElement),
    planetA: mustGetAs("planetA", HTMLInputElement),
    planetE: mustGetAs("planetE", HTMLInputElement),
    planetInc: mustGetAs("planetInc", HTMLInputElement),
    planetPeriod: mustGetAs("planetPeriod", HTMLInputElement),
    planetMass: mustGetAs("planetMass", HTMLInputElement),
    planetPhaseEnabled: mustGetAs("planetPhaseEnabled", HTMLInputElement),
    planetReflAmp: mustGetAs("planetReflAmp", HTMLInputElement),
    planetThermAmp: mustGetAs("planetThermAmp", HTMLInputElement),
    planetReflOffset: mustGetAs("planetReflOffset", HTMLInputElement),
    planetThermOffset: mustGetAs("planetThermOffset", HTMLInputElement),
    planetLambertian: mustGetAs("planetLambertian", HTMLInputElement),
    planetConstant: mustGetAs("planetConstant", HTMLInputElement),
    planetThermalInertiaEnabled: mustGetAs("planetThermalInertiaEnabled", HTMLInputElement),
    planetAlbedo: mustGetAs("planetAlbedo", HTMLInputElement),
    planetEmissivity: mustGetAs("planetEmissivity", HTMLInputElement),
    planetThermalTimescale: mustGetAs("planetThermalTimescale", HTMLInputElement),
    planetRedistribution: mustGetAs("planetRedistribution", HTMLInputElement),
    planetOblateEnabled: mustGetAs("planetOblateEnabled", HTMLInputElement),
    planetOblateness: mustGetAs("planetOblateness", HTMLInputElement),
    planetRingsEnabled: mustGetAs("planetRingsEnabled", HTMLInputElement),
    planetRingInner: mustGetAs("planetRingInner", HTMLInputElement),
    planetRingOuter: mustGetAs("planetRingOuter", HTMLInputElement),
    planetRingInc: mustGetAs("planetRingInc", HTMLInputElement),
    planetRingAngle: mustGetAs("planetRingAngle", HTMLInputElement),
    fsEnabled: mustGetAs("fsEnabled", HTMLInputElement),
    fsAmp: mustGetAs("fsAmp", HTMLInputElement),
    fsG: mustGetAs("fsG", HTMLInputElement),
    fsSigma: mustGetAs("fsSigma", HTMLInputElement),
    fsOffset: mustGetAs("fsOffset", HTMLInputElement),
    fsGateBehind: mustGetAs("fsGateBehind", HTMLInputElement),
    atmEnabled: mustGetAs("atmEnabled", HTMLInputElement),
    atmKind: mustGetAs("atmKind", HTMLSelectElement),
    atmR0: mustGetAs("atmR0", HTMLInputElement),
    atmH: mustGetAs("atmH", HTMLInputElement),
    atmTau0: mustGetAs("atmTau0", HTMLInputElement),
    atmLambdaNm: mustGetAs("atmLambdaNm", HTMLInputElement),
    atmTauScale: mustGetAs("atmTauScale", HTMLInputElement),
    moonEnabled: mustGetAs("moonEnabled", HTMLInputElement),
    moonR: mustGetAs("moonR", HTMLInputElement),
    moonA: mustGetAs("moonA", HTMLInputElement),
    moonE: mustGetAs("moonE", HTMLInputElement),
    moonInc: mustGetAs("moonInc", HTMLInputElement),
    moonPeriod: mustGetAs("moonPeriod", HTMLInputElement),
    moonMass: mustGetAs("moonMass", HTMLInputElement),
    moonPhaseEnabled: mustGetAs("moonPhaseEnabled", HTMLInputElement),
    moonReflAmp: mustGetAs("moonReflAmp", HTMLInputElement),
    moonThermAmp: mustGetAs("moonThermAmp", HTMLInputElement),
    moonLambertian: mustGetAs("moonLambertian", HTMLInputElement),
    moonThermalInertiaEnabled: mustGetAs("moonThermalInertiaEnabled", HTMLInputElement),
    moonAlbedo: mustGetAs("moonAlbedo", HTMLInputElement),
    moonEmissivity: mustGetAs("moonEmissivity", HTMLInputElement),
    moonThermalTimescale: mustGetAs("moonThermalTimescale", HTMLInputElement),
    moonRedistribution: mustGetAs("moonRedistribution", HTMLInputElement),
    moonOblateEnabled: mustGetAs("moonOblateEnabled", HTMLInputElement),
    moonOblateness: mustGetAs("moonOblateness", HTMLInputElement),
    moonRingsEnabled: mustGetAs("moonRingsEnabled", HTMLInputElement),
    moonRingInner: mustGetAs("moonRingInner", HTMLInputElement),
    moonRingOuter: mustGetAs("moonRingOuter", HTMLInputElement),
    moonRingInc: mustGetAs("moonRingInc", HTMLInputElement),
    moonRingAngle: mustGetAs("moonRingAngle", HTMLInputElement),
    smearEnabled: mustGetAs("smearEnabled", HTMLInputElement),
    cadenceSec: mustGetAs("cadenceSec", HTMLInputElement),
    nSubsamples: mustGetAs("nSubsamples", HTMLInputElement),
    varEnabled: mustGetAs("varEnabled", HTMLInputElement),
    beamingAmp: mustGetAs("beamingAmp", HTMLInputElement),
    ellipsoidalAmp: mustGetAs("ellipsoidalAmp", HTMLInputElement),
    beamingOffset: mustGetAs("beamingOffset", HTMLInputElement),
    ellipsoidalOffset: mustGetAs("ellipsoidalOffset", HTMLInputElement),
    varConstant: mustGetAs("varConstant", HTMLInputElement),
    dnEnabled: mustGetAs("dnEnabled", HTMLInputElement),
    dnClamp: mustGetAs("dnClamp", HTMLInputElement),
    dnReflectedModel: mustGetAs("dnReflectedModel", HTMLSelectElement),
    dnThermalModel: mustGetAs("dnThermalModel", HTMLSelectElement),
    exoEnabled: mustGetAs("exoEnabled", HTMLInputElement),
    exoTRef: mustGetAs("exoTRef", HTMLInputElement),
    exoVelDt: mustGetAs("exoVelDt", HTMLInputElement),
    exoMoonOmegaDot: mustGetAs("exoMoonOmegaDot", HTMLInputElement),
    exoMoonIncDot: mustGetAs("exoMoonIncDot", HTMLInputElement),
    exoMoonOmegaSmallDot: mustGetAs("exoMoonOmegaSmallDot", HTMLInputElement),
    exoImpactYDot: mustGetAs("exoImpactYDot", HTMLInputElement),
    nbodyEnabled: mustGetAs("nbodyEnabled", HTMLInputElement),
    nbodyMuStar: mustGetAs("nbodyMuStar", HTMLInputElement),
    nbodyMuPlanet: mustGetAs("nbodyMuPlanet", HTMLInputElement),
    nbodyMuMoon: mustGetAs("nbodyMuMoon", HTMLInputElement),
    nbodyDtMax: mustGetAs("nbodyDtMax", HTMLInputElement),
    nbodySoftening: mustGetAs("nbodySoftening", HTMLInputElement),
    pert1Enabled: mustGetAs("pert1Enabled", HTMLInputElement),
    pert1Mu: mustGetAs("pert1Mu", HTMLInputElement),
    pert1A: mustGetAs("pert1A", HTMLInputElement),
    pert1E: mustGetAs("pert1E", HTMLInputElement),
    pert1Inc: mustGetAs("pert1Inc", HTMLInputElement),
    pert1Period: mustGetAs("pert1Period", HTMLInputElement),
    pert2Enabled: mustGetAs("pert2Enabled", HTMLInputElement),
    pert2Mu: mustGetAs("pert2Mu", HTMLInputElement),
    pert2A: mustGetAs("pert2A", HTMLInputElement),
    pert2E: mustGetAs("pert2E", HTMLInputElement),
    pert2Inc: mustGetAs("pert2Inc", HTMLInputElement),
    pert2Period: mustGetAs("pert2Period", HTMLInputElement),
    relEnabled: mustGetAs("relEnabled", HTMLInputElement),
    relLTTE: mustGetAs("relLTTE", HTMLInputElement),
    relShapiro: mustGetAs("relShapiro", HTMLInputElement),
    relGR: mustGetAs("relGR", HTMLInputElement),
    relC: mustGetAs("relC", HTMLInputElement),
    relPlanetPrec: mustGetAs("relPlanetPrec", HTMLInputElement),
    relMoonPrec: mustGetAs("relMoonPrec", HTMLInputElement),
  };
}

export const uiRefs = new Proxy({} as UiRefs, {
  get(_target, prop) {
    return createUiRefs()[prop as keyof UiRefs];
  },
  has(_target, prop) {
    return prop in createUiRefs();
  },
  ownKeys() {
    return Reflect.ownKeys(createUiRefs());
  },
  getOwnPropertyDescriptor(_target, prop) {
    const refs = createUiRefs();
    return {
      configurable: true,
      enumerable: true,
      value: refs[prop as keyof UiRefs],
    };
  },
}) as UiRefs;
